"""Markdown-native factories for Context, Skills, Agents, and Loops.

Factories materialize reviewable Markdown artifacts only. External Hermes side
 effects (profile creation, cron creation, skill installation) are intentionally
 represented by adapter records and require a separate approved executor.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re

from .model import Proposal


@dataclass(frozen=True)
class Materialized:
    primitive: str
    slug: str
    path: Path


def _safe_slug(value: str) -> str:
    value = re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")
    return value or "untitled"


def _topic_root(root: Path, slug: str) -> Path:
    topic = root / "topics" / _safe_slug(slug)
    for directory in (".system", "skills", "agents", "loops"):
        (topic / directory).mkdir(parents=True, exist_ok=True)
    return topic


def _append(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if text.strip() in existing:
            return
        path.write_text(existing.rstrip() + "\n\n" + text.strip() + "\n", encoding="utf-8")
    else:
        path.write_text(text.strip() + "\n", encoding="utf-8")


def materialize_context(root: str | Path, topic: str, proposals: list[Proposal]) -> Materialized:
    target = _topic_root(Path(root), topic)
    lines = [f"# {topic.title()}", "", "> Context dashboard generated by Senter Agent.", "", "## Evidence"]
    for proposal in proposals:
        lines.append(f"- `{proposal.primitive}:{proposal.slug}` — {proposal.reason}")
    (target / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return Materialized("context", _safe_slug(topic), target / "README.md")


def materialize_proposal(root: str | Path, topic: str, proposal: Proposal) -> Materialized:
    target = _topic_root(Path(root), topic)
    directory = {"skill": "skills", "agent": "agents", "loop": "loops", "context": ".system"}[proposal.primitive]
    suffix = "SKILL.md" if proposal.primitive == "skill" else "README.md"
    path = target / directory / f"{_safe_slug(proposal.slug)}-{suffix}" if suffix != "README.md" else target / directory / f"{_safe_slug(proposal.slug)}.md"
    heading = proposal.slug.replace("-", " ").title()
    if proposal.primitive == "skill":
        content = f"---\nname: {_safe_slug(proposal.slug)}\ndescription: {proposal.reason}\n---\n\n# {heading}\n\n## Status\n\nProposed; review before installing.\n\n## Evidence\n\n" + "\n".join(f"- `{source}`" for source in proposal.source_documents)
    else:
        content = f"# {heading}\n\n- **Primitive:** `{proposal.primitive}`\n- **Status:** proposed\n- **Reason:** {proposal.reason}\n\n## Evidence\n" + "\n".join(f"- `{source}`" for source in proposal.source_documents)
    _append(path, content)
    return Materialized(proposal.primitive, proposal.slug, path)


def materialize_all(root: str | Path, topic: str, proposals: list[Proposal]) -> list[Materialized]:
    """Materialize every reviewed proposal as editable Markdown."""
    result = [materialize_context(root, topic, proposals)]
    result.extend(materialize_proposal(root, topic, proposal) for proposal in proposals)
    return result


__all__ = ["Materialized", "materialize_all", "materialize_context", "materialize_proposal"]
